In [1]:
from mxnet import autograd, nd

In [5]:
x = nd.arange(4).reshape((4, 1))
x.attach_grad()#申请储存梯度所需内存，mxnet不会自动分配
with autograd.record():
    y = 2 * nd.dot(x.T, x)
y.backward()
assert(x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

## 对Python控制流求梯度

In [24]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000: #\\b\\是否小于1000
        b = b * 2
    if b.sum().asscalar() > 0: #.asscalar()：把这个 NDArray 标量拉成 Python 标量（float）
        c = b
    else:
        c = 100 * b
    return c
a = nd.array([[1., 2.],
              [3., 4.]])
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()
a.grad


[[2. 4.]
 [6. 8.]]
<NDArray 2x2 @cpu(0)>



[[256. 256.]
 [256. 256.]]
<NDArray 2x2 @cpu(0)>

## 链式传播
https://www.bilibili.com/video/BV1QAjmzCEgx/