In [26]:
from mxnet import nd
X = nd.arange(12)
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
#X.reshape(3, 4) < Y


[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [5]:
nd.zeros((2, 3, 4)),
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [7]:
nd.random.normal(0, 1, shape=(3, 4))#均值为0，标准差为1，3行4列


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [13]:
nd.dot(X, Y.T) #做矩阵乘法，X*Y就是把对应位置上的数相乘


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [14]:
nd.concat(X, Y, dim=0)#6行4列


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [16]:
X==Y#每个位置比较后返回0或1
X.sum()#整个求和


[66.]
<NDArray 1 @cpu(0)>

# 广播机制

In [20]:
A = nd.arange(3).reshape(3, 1)
B = nd.arange(2).reshape(1, 2)
A+B#变成3行2列,A+B==B+A,多出的行和列是复制的本身的，而不是补0



[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [4]:
X[1:3]#行[1,3)，等价于X[1:3, :],列索引省略


[1. 2.]
<NDArray 2 @cpu(0)>

# 内存分配

In [19]:
X = X.reshape((3, 4))#(1,12)和（3，4）不能广播
before = id(Y)
Y = Y + X # Y+=X则不会占用额外的内存
id(Y) == before

False